### ISSUE TITLE
Sorting in descending order doesn't work

### ISSUE THREAD

**Issue by malaire** [shannah/xataface-module-depselect#1]
Select-list can't be sorted in descending order.

When I try to use

    widget:filters:-sort = "FieldName desc"

the resulting select-list has no items.

**Comment by shannah** [comment]
Is there an error in your PHP error log?

**Comment by malaire** [comment]
Actually yes, sorry I forgot to check at first:

[Mon Jul 17 22:17:17.553459 2017] [:error] [pid 7781] [client 127.0.0.1:35260] PHP Fatal error:  Uncaught Exception: Failed to load current record due to an SQL error in /y/srv/xataface/xataface-2.1.3/Dataface/QueryTool.php:532
Stack trace:
#0 /y/srv/xataface/xataface-2.1.3/Dataface/Application.php(1359): Dataface_QueryTool->loadCurrent()
#1 /y/srv/xataface/xataface-2.1.3/Dataface/Application.php(3069): Dataface_Application->getRecord()
#2 /y/srv/xataface/xataface-2.1.3/Dataface/Application.php(3098): Dataface_Application->getPermissions()
#3 /y/srv/xataface/xataface-2.1.3/Dataface/ActionTool.php(237): Dataface_Application->checkPermission('list')
#4 /y/srv/xataface/xataface-2.1.3/Dataface/Table.php(5708): Dataface_ActionTool->getActions(Array)
#5 /y/srv/xataface/xataface-2.1.3/Dataface/ActionTool.php(81): Dataface_Table->getActions(Array)
#6 /y/srv/xataface/xataface-2.1.3/Dataface/ActionTool.php(97): Dataface_ActionTool->_loadTableActions('ZdoEdition')
#7 /y/srv/xataface/xataface-2.1.3/Dataface/Application.php(2269): Dataface_ActionTool->getAction(Array)
#8 /y/srv/xataface/xataface-2.1.3/Dataface/Applic in /y/srv/xataface/xataface-2.1.3/Dataface/QueryTool.php on line 532, referer: https://dev.amolelingue/admin/xataface/index.php?-table=RaiVideo&-action=edit&-cursor=0&-skip=0&-limit=30&-mode=list&-recordid=RaiVideo%3FRaiVideoID%3D1

Exact definition at fields.ini:

    [ZdoEditionID]
    visibility:browse        = hidden
    visibility:list          = hidden
    widget:filters:-sort     = "ZdoEditionID DESC"
    widget:keycol            = ZdoEditionID
    widget:labelcol          = MyTitle
    widget:table             = ZdoEdition
    widget:type              = depselect

And fields definitions are

    ZdoEditionID tinyint(2) unsigned PRIMARY
    MyTitle varchar(50)
